### ISSUE TITLE
Emoji 15 🪿

### ISSUE THREAD

**Issue by DysphoricUnicorn** [Mange/emoji-data#19]
Last year [Emoji 15](https://unicode.org/emoji/charts-15.0/emoji-released.html) was released and it has gotten quite a bit of attention recently since apple used it to "sell" their users an important security update.

From what I can see, the latest version of emoji-data added emoji 14 and rofi-emoji, which uses the library from emoji-data, does not yet support the new emoji, so I think they are missing here currently.

**Comment by Mange** [comment]
Thanks for letting me know! I just released a new version of both `emoji-data` and of `rofi-emoji` with those new emojis included.

> Last year [Emoji 15](https://unicode.org/emoji/charts-15.0/emoji-released.html) was released and it has gotten quite a bit of attention recently since apple used it to "sell" their users an important security update.

Haha! Apple being Apple as usual! :facepalm: :laughing:
