### ISSUE TITLE
make all throws an error

### ISSUE THREAD

**Issue by rainypixels** [Mange/emoji-data#4]
This is what I got when I run `make all`:
```
$ make all
make: *** No rule to make target `cldr/tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt', needed by `data/all.json'.  Stop.
```

So then I tried to run `make cldr`, but that failed because there's already an empty `cldr` folder in the cloned repo. Deleting the empty folder and running `make cldr` succeeded in cloning the cldr repo, and consequently unblocked `make all` from running. 

Thanks for this repo, btw. It's exactly what I was searching for to generate a swift enum of the full emoji character set. It's particularly great that you've added the cldr repo as a submodule to allow for future updates. 💯

**Comment by Mange** [comment]
Thank you! ❤️

Do you know how you ended up in this state? Straight away when you cloned?

I think I could rework the targets so it checks for the presence of a few files in the directory too and recovers this automatically.

Thank you for the report!

**Comment by rainypixels** [comment]
Yep, straight from the clone. I almost considered doing a PR but my `make` skills are rusty 😬

**Comment by Mange** [comment]
Clearly mine are too! :smile: 

Fix coming soon.
