### ISSUE TITLE
all_emojis.json is not valid json

### ISSUE THREAD

**Issue by rainypixels** [Mange/emoji-data#5]
The file is currently just a bunch of arrays of json objects. Each one of the arrays represents a category. I went ahead and deleted the arrays, and folded all the objects into one array as follows:

```
[
  {
    "characters": "😀",
    "name": "grinning face",
    "category_name": "Smileys & Emotion",
    "subcategory_name": "face-smiling",
    "en_keywords": [
      "face",
      "grin",
      "grinning face"
    ],
    "qualification": "fully-qualified"
  },
  ...,
  {
    "characters": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "name": "flag: Wales",
    "category_name": "Flags",
    "subcategory_name": "subdivision-flag",
    "en_keywords": [
      "flag"
    ],
    "qualification": "fully-qualified"
  }
]
```

I think this makes more sense for the data file structure since you can easily key by any of the object properties in the flattened array to slice it.

**Comment by Mange** [comment]
That is exactly the format specified in the README, which was a copy-paste from the real generated JSON file.

I suspect something broke at some point if the file now contains a stream of JSON arrays instead of one large array.

I will take a look at this!

**Comment by rainypixels** [comment]
Doh, that's right. I remember seeing that in the README (which was a big part of why I decided to use emoji-data).

**Comment by Mange** [comment]
So I did a fresh clone and regenerated the files, but the resulting `all_emojis.json` file is valid JSON. The JSON document is of a single array of objects.

```
› cat data/all_emojis.json | jq > /dev/null; echo $?
0
```

Do you get this same result? Could it be that the tool you are using to read the document requires the root type to be an object?

**Comment by rainypixels** [comment]
Apologies for the delay in verifying. Been a week. I'll circle back this coming week...

**Comment by rainypixels** [comment]
Hmmmmm... 🤔 So, the good news: `make all` worked like a champ. 🎉 But, I'm still seeing the multiple arrays of objects where each array is a category. I opened the file in atom, textedit, and finally vim because I was worried that maybe the former two were modifying the file. Notice in the screenshot where the _Smileys and Emotion_ array ends, and the _People & Body_ array starts. This happens per category. What am I missing? 

p.s. FWIW, this is not a huge deal for me. It's simple enough to merge the arrays manually before I bring the file into my own script that converts this to a Swift `enum`.

<img width="930" alt="all-emojis-vim" src="https://user-images.githubusercontent.com/780433/68817795-b81b8280-0637-11ea-8606-2c2642736604.png">

**Comment by Mange** [comment]
Thank you. I can now confirm the issue!
![Skärmbild från 2019-11-14 20-31-23](https://user-images.githubusercontent.com/1599/68889722-c217b100-071d-11ea-87a3-36ac30a72287.png)

I'll see if I can figure out why this happens.

**Comment by Mange** [comment]
This should now be fixed in `master`. Please check it out.

I'll release a new patch release later if you can confirm this works better for you. Thank you for your persistence! I love being proved wrong.

**Comment by rainypixels** [comment]
Just `git pull`ed and `make all`ed, and I am happy to report that it is indeed fixed! 💯Thanks for doing the hard work, @Mange. Upwards and onwards.
